package model;
// Generated 1/03/2016 11:02:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * InformacionUsuario generated by hbm2java
 */
@Entity
@Table(name="informacion_usuario"
    ,schema="public"
)
public class InformacionUsuario  implements java.io.Serializable {


     private int idUsuario;
     private Usuario usuario;
     private String nombreUsuario;
     private String apellidoPaternoUsuario;
     private String apellidoMaternoUsuario;

    public InformacionUsuario() {
    }

    public InformacionUsuario(Usuario usuario, String nombreUsuario, String apellidoPaternoUsuario, String apellidoMaternoUsuario) {
       this.usuario = usuario;
       this.nombreUsuario = nombreUsuario;
       this.apellidoPaternoUsuario = apellidoPaternoUsuario;
       this.apellidoMaternoUsuario = apellidoMaternoUsuario;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="usuario"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombre_usuario", nullable=false, length=30)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="apellido_paterno_usuario", nullable=false, length=30)
    public String getApellidoPaternoUsuario() {
        return this.apellidoPaternoUsuario;
    }
    
    public void setApellidoPaternoUsuario(String apellidoPaternoUsuario) {
        this.apellidoPaternoUsuario = apellidoPaternoUsuario;
    }

    
    @Column(name="apellido_materno_usuario", nullable=false, length=30)
    public String getApellidoMaternoUsuario() {
        return this.apellidoMaternoUsuario;
    }
    
    public void setApellidoMaternoUsuario(String apellidoMaternoUsuario) {
        this.apellidoMaternoUsuario = apellidoMaternoUsuario;
    }




}


