package model;
// Generated 1/03/2016 11:02:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String correoElectronico;
     private String contraseña;
     private InformacionUsuario informacionUsuario;

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String correoElectronico, String contraseña) {
        this.idUsuario = idUsuario;
        this.correoElectronico = correoElectronico;
        this.contraseña = contraseña;
    }
    public Usuario(int idUsuario, String correoElectronico, String contraseña, InformacionUsuario informacionUsuario) {
       this.idUsuario = idUsuario;
       this.correoElectronico = correoElectronico;
       this.contraseña = contraseña;
       this.informacionUsuario = informacionUsuario;
    }
   
     @Id 

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="correo_electronico", nullable=false, length=100)
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    
    @Column(name="contraseña", nullable=false, length=30)
    public String getContraseña() {
        return this.contraseña;
    }
    
    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="usuario")
    public InformacionUsuario getInformacionUsuario() {
        return this.informacionUsuario;
    }
    
    public void setInformacionUsuario(InformacionUsuario informacionUsuario) {
        this.informacionUsuario = informacionUsuario;
    }




}


